language: python
python:
- '3.6'
- '3.7'
- '3.8'
before_install:
- pip install -r requirements.txt
- pip install -r test_requirements.txt
install:
- pip install -e .
script:
- pytest
deploy:
  provider: pypi
  user: __token__
  password:
    secure: Pl3dkfXtEbd7TEg+DVIIQ8lo1sZh7uSISDPlJOExAG0ndaHHc3zqiDXC8SxioMJ86E7c1OTZTGmtNuA0b3bicCaolveBvuGewoOXBerOFUHvjbAODsZ5uEDPebhTi3J/M7Gn2cOJapAxlv3vokQUIy5BVdQ+d20+MTZgn52nVwni2pl4oh6gaPlXQbVqvTyySkPQ+zr2FJlaKgn8hkPk3AtAK3obplLnnfSLXzS75P5CzpJTNQXAahdIEXX0HP4RN5/YiCGkKE4M0Yv0A1YO9EVj3ZF8TtZvvs+XFfJKlf/2fNt2iWqk+hLr4Zisy3/DbcOPuAqbQsq4kj42AxJQ8U5yMVlQfIIC6rrguXn0plkZ1YEJUA8gGO4a4U5bzzmtoj3s7nLS5JFWYPqXNgTD5c0CVKyGE59wSD1w8RjH4hbayg+o5D4D1pQbFa5m81W2uHlIh9zC9lWNCRQiMK398aLuvA6waTQBuyO52AqevBPVagJqdiD1NPzMXOvWVd+VNC704PHb0kZw4hZ+F6oMsuBHTEDK/Z+dm27py26fdOnlwYBYdroEmQYBpNeWozDIqbQqbMdZez0eurwmdl77LPzKX2fvPWFmkSG8ZBCXlv3fsBNhBefjYIviLNCAyK7ATsIpfdkHVau4vV+EzGCT/3EYCzapTg11jRcQVqn2QL4=
  on:
    tags: true
  skip_existing: true
